/**
 * moduleRegistry.js
 *
 * Single source of truth for every module under test.
 * Adding a new module = one entry here. Zero other changes needed.
 *
 * Each entry describes:
 *   name        — human label used in test output
 *   servicePath — relative path to the service module (from __tests__/helpers/)
 *   httpPath    — Express route prefix (for integration tests)
 *   exports     — maps canonical names → actual exported function names
 *                 (handles both standard exports and named-export services)
 *   createData  — minimal valid payload for CREATE
 *   updateData  — minimal valid payload for UPDATE (non-empty patch)
 *   existingRow — extra fields the SELECT_BY_ID mock should carry
 *                 (mirrors what prepareUpdateParams reads from `existing`)
 */

const UUID = 'a1b2c3d4-1111-1111-1111-111111111111';

// Standard export shape shared by most services
const STD = {
  create:  'create',
  update:  'update',
  getAll:  'getAll',
  getById: 'getById',
  delete:  'delete',
};

// POS services expose delete as `remove` (the rest match STD).
const POS = {
  create:  'create',
  update:  'update',
  getAll:  'getAll',
  getById: 'getById',
  delete:  'remove',
};

const registry = [
  // ─── Master / reference tables ────────────────────────────────────────────
  {
    name: 'accounttype',
    servicePath: '../../modules/accounttype/accounttype.service',
    httpPath: '/api/accounttypes',
    exports: STD,
    createData:  { Name: 'Expense', Active: true },
    updateData:  { Name: 'Revenue' },
    existingRow: { Name: 'OldExpense' },
  },
  {
    name: 'accounttypebase',
    servicePath: '../../modules/accounttypebase/accounttypebase.service',
    httpPath: '/api/accounttypebases',
    exports: STD,
    createData:  { Name: 'Sales', Active: true },
    updateData:  { Name: 'Purchase' },
    existingRow: { Name: 'OldSales' },
  },
  {
    name: 'taxtype',
    servicePath: '../../modules/taxtype/taxtype.service',
    httpPath: '/api/taxtypes',
    exports: { create: 'createTaxType', update: 'updateTaxType', getAll: 'getAllTaxTypes', getById: 'getTaxTypeById', delete: 'deleteTaxType' },
    createData:  { Name: 'GST', Value: '18', Active: true },
    updateData:  { Name: 'IGST' },
    existingRow: { Name: 'GST', Value: '18' },
  },
  {
    name: 'uom',
    servicePath: '../../modules/uom/uom.service',
    httpPath: '/api/uom',
    exports: { create: 'createUom', update: 'updateUom', getAll: 'getAllUom', getById: 'getUomById', delete: 'deleteUom' },
    createData:  { UnitName: 'KG', IsPrimary: false, Active: true },
    updateData:  { UnitName: 'LB' },
    existingRow: { UnitName: 'KG', IsPrimary: 0 },
  },
  {
    name: 'category',
    servicePath: '../../modules/category/category.service',
    httpPath: '/api/categories',
    exports: { create: 'createCategory', update: 'updateCategory', getAll: 'getAllCategories', getById: 'getCategoryById', delete: 'deleteCategory' },
    createData:  { Name: 'Electronics', Active: true },
    updateData:  { Name: 'Appliances' },
    existingRow: { Name: 'Electronics' },
  },
  {
    name: 'transactiontypeconfig',
    servicePath: '../../modules/transactiontypeconfig/transactiontypeconfig.service',
    httpPath: '/api/transactiontypeconfigs',
    exports: STD,
    createData:  { StartCounterNo: '1001', Prefix: 'INV', Format: 'INV-{SEQ}', TagName: null, Active: true },
    updateData:  { Prefix: 'PO' },
    existingRow: { StartCounterNo: '1001', Prefix: 'INV', Format: 'INV-{SEQ}', TagName: null },
  },
  {
    name: 'organization',
    servicePath: '../../modules/organization/organization.service',
    httpPath: '/api/organizations',
    exports: STD,
    createData:  { Name: 'Acme Corp', Active: true },
    updateData:  { Name: 'Beta Ltd' },
    existingRow: { Name: 'Acme Corp' },
  },
  {
    name: 'uomfactor',
    servicePath: '../../modules/uomfactor/uomfactor.service',
    httpPath: '/api/uomfactors',
    exports: STD,
    createData:  { PrimaryUOMId: UUID, SecondaryUOMId: UUID, Factor: '1000', Active: true },
    updateData:  { Factor: '500' },
    existingRow: { PrimaryUOMId: UUID, SecondaryUOMId: UUID, Factor: '1000' },
  },
  {
    name: 'transactiontype',
    servicePath: '../../modules/transactiontype/transactiontype.service',
    httpPath: '/api/transactiontypes',
    exports: STD,
    createData:  { Name: 'Sales Invoice', TransactionTypeConfigId: UUID, Active: true },
    updateData:  { Name: 'Purchase Invoice' },
    existingRow: { Name: 'Sales Invoice', TransactionTypeConfigId: UUID },
  },
  {
    name: 'transactiontypestatus',
    servicePath: '../../modules/transactiontypestatus/transactiontypestatus.service',
    httpPath: '/api/transactiontypestatuses',
    exports: STD,
    createData:  { Name: 'Pending', Active: true },
    updateData:  { Name: 'Approved' },
    existingRow: { Name: 'Pending' },
  },
  {
    name: 'contactaddresstype',
    servicePath: '../../modules/contactaddresstype/contactaddresstype.service',
    httpPath: '/api/contactaddresstypes',
    exports: STD,
    createData:  { Name: 'Home', Active: true },
    updateData:  { Name: 'Office' },
    existingRow: { Name: 'Home' },
  },
  {
    name: 'taxgroup',
    servicePath: '../../modules/taxgroup/taxgroup.service',
    httpPath: '/api/taxgroups',
    exports: STD,
    createData:  { Name: 'GST 18%', Active: true },
    updateData:  { Name: 'GST 5%' },
    existingRow: { Name: 'GST 18%' },
  },
  {
    name: 'taxgrouptaxtypemapper',
    servicePath: '../../modules/taxgrouptaxtypemapper/taxgrouptaxtypemapper.service',
    httpPath: '/api/taxgrouptaxtypemappers',
    exports: STD,
    createData:  { TaxGroupId: UUID, TaxTypeId: UUID, Active: true },
    updateData:  { Active: false },
    existingRow: { TaxGroupId: UUID, TaxTypeId: UUID },
  },
  {
    name: 'mapprovider',
    servicePath: '../../modules/mapprovider/mapprovider.service',
    httpPath: '/api/mapproviders',
    exports: STD,
    createData:  { ProviderName: 'Google Maps', Active: true },
    updateData:  { ProviderName: 'Bing Maps' },
    existingRow: { ProviderName: 'Google Maps' },
  },
  {
    name: 'locationdetail',
    servicePath: '../../modules/locationdetail/locationdetail.service',
    httpPath: '/api/locationdetails',
    exports: STD,
    createData:  { Lat: '12.9716', Lng: '77.5946', Active: true },
    updateData:  { Lat: '13.0000' },
    existingRow: { Lat: '12.9716', Lng: '77.5946' },
  },
  {
    name: 'mapproviderlocationmapper',
    servicePath: '../../modules/mapproviderlocationmapper/mapproviderlocationmapper.service',
    httpPath: '/api/mapproviderlocationmappers',
    exports: STD,
    createData:  { MapProviderId: UUID, LocationDetailId: UUID, TagName: 'WAREHOUSE', Active: true },
    updateData:  { TagName: 'BRANCH' },
    existingRow: { MapProviderId: UUID, LocationDetailId: UUID, TagName: 'WAREHOUSE' },
  },
  {
    name: 'contactdetail',
    servicePath: '../../modules/contactdetail/contactdetail.service',
    httpPath: '/api/contactdetails',
    exports: STD,
    createData:  { FirstName: 'John', LastName: 'Doe', Active: true },
    updateData:  { FirstName: 'Jane' },
    existingRow: { FirstName: 'John', LastName: 'Doe' },
  },
  {
    name: 'addressdetail',
    servicePath: '../../modules/addressdetail/addressdetail.service',
    httpPath: '/api/addressdetails',
    exports: STD,
    createData:  { AddressLine1: null, MapProviderLocationMapperId: UUID, ContactAddressTypeId: UUID, TagName: null, Active: true },
    updateData:  { City: 'Mumbai' },
    existingRow: { MapProviderLocationMapperId: UUID, ContactAddressTypeId: UUID, City: 'Bengaluru', TagName: null },
  },
  {
    name: 'costinfo',
    servicePath: '../../modules/costinfo/costinfo.service',
    httpPath: '/api/costinfos',
    exports: STD,
    createData:  { Amount: '1000.00', TaxGroupId: UUID, IsTaxIncluded: false, Active: true },
    updateData:  { Amount: '2000.00' },
    existingRow: { Amount: '1000.00', TaxGroupId: UUID, IsTaxIncluded: 0 },
  },
  {
    name: 'branchdetail',
    servicePath: '../../modules/branchdetail/branchdetail.service',
    httpPath: '/api/branchdetails',
    exports: STD,
    createData:  { OrganizationDetailId: UUID, ContactDetailId: UUID, AddressDetailId: UUID, TransactionTypeConfigId: UUID, BranchName: 'HQ', Active: true },
    updateData:  { BranchName: 'Regional Office' },
    existingRow: { OrganizationDetailId: UUID, ContactDetailId: UUID, AddressDetailId: UUID, TransactionTypeConfigId: UUID, BranchName: 'HQ' },
  },
  {
    name: 'branchusergroupmapper',
    servicePath: '../../modules/branchusergroupmapper/branchusergroupmapper.service',
    httpPath: '/api/branchusergroupmappers',
    exports: STD,
    createData:  { BranchDetailId: UUID, UserGroupId: UUID, Active: true },
    updateData:  { Active: false },
    existingRow: { BranchDetailId: UUID, UserGroupId: UUID },
  },
  {
    name: 'batchdetail',
    servicePath: '../../modules/batchdetail/batchdetail.service',
    httpPath: '/api/batchdetails',
    exports: STD,
    createData:  { BatchNo: 'BATCH-001', IsNonReturnable: false, Active: true },
    updateData:  { BatchNo: 'BATCH-002' },
    existingRow: { BatchNo: 'BATCH-001', IsNonReturnable: 0, MfgDate: null, Expdate: null, PurchaseDate: null },
  },
  {
    name: 'itemdetail',
    servicePath: '../../modules/itemdetail/itemdetail.service',
    httpPath: '/api/itemdetails',
    exports: STD,
    createData:  { Name: 'Widget A', Active: true },
    updateData:  { Name: 'Widget B' },
    existingRow: { Name: 'Widget A', Code: null, SKU: null },
  },
  {
    name: 'transactiontypebaseconversion',
    servicePath: '../../modules/transactiontypebaseconversion/transactiontypebaseconversion.service',
    httpPath: '/api/transactiontypebaseconversions',
    exports: STD,
    createData:  { TransactionTypeConfigId: UUID, FromTransactionTypeStatusId: UUID, ToTransactionTypeStatusId: UUID, Tag: 'TAG', Active: true },
    updateData:  { Tag: 'NEW_TAG' },
    existingRow: { TransactionTypeConfigId: UUID, FromTransactionTypeStatusId: UUID, ToTransactionTypeStatusId: UUID, Tag: 'TAG' },
  },
  {
    name: 'transactiondetaillog',
    servicePath: '../../modules/transactiondetaillog/transactiondetaillog.service',
    httpPath: '/api/transactiondetaillogs',
    exports: STD,
    createData:  { TransactionNo: 'INV-001', TransactionTypeConfigId: UUID, TransactionDate: '2026-05-31', Active: true },
    updateData:  { Remarks: 'Updated' },
    existingRow: { TransactionNo: 'INV-001', TransactionTypeConfigId: UUID, TransactionDate: '2026-05-31' },
  },
  {
    name: 'transactionitemdetail',
    servicePath: '../../modules/transactionitemdetail/transactionitemdetail.service',
    httpPath: '/api/transactionitemdetails',
    exports: STD,
    createData:  { TransactionDetailLogId: UUID, ItemId: UUID, Active: true },
    updateData:  { Comment: 'Updated' },
    existingRow: { TransactionDetailLogId: UUID, ItemId: UUID, Comment: null },
  },
  {
    name: 'transactiontypeconversionmapper',
    servicePath: '../../modules/transactiontypeconversionmapper/transactiontypeconversionmapper.service',
    httpPath: '/api/transactiontypeconversionmappers',
    exports: STD,
    createData:  { TransactionTypeBaseCoversionId: UUID, TransactionDetailLogId: UUID, TransactionTypeStatusId: UUID, Active: true },
    updateData:  { Active: false },
    existingRow: { TransactionTypeBaseCoversionId: UUID, TransactionDetailLogId: UUID, TransactionTypeStatusId: UUID },
  },
  {
    name: 'paymentreceivedtype',
    servicePath: '../../modules/paymentreceivedtype/paymentreceivedtype.service',
    httpPath: '/api/paymentreceivedtypes',
    exports: STD,
    createData:  { Type: 'Full Payment', Active: true },
    updateData:  { Type: 'Partial' },
    existingRow: { Type: 'Full Payment' },
  },
  {
    name: 'paymentmode',
    servicePath: '../../modules/paymentmode/paymentmode.service',
    httpPath: '/api/paymentmodes',
    exports: STD,
    createData:  { Type: 'Cash', Active: true },
    updateData:  { Type: 'Card' },
    existingRow: { Type: 'Cash' },
  },
  {
    name: 'paymentmodetransactiondetail',
    servicePath: '../../modules/paymentmodetransactiondetail/paymentmodetransactiondetail.service',
    httpPath: '/api/paymentmodetransactiondetails',
    exports: STD,
    createData:  { PaymentModeId: UUID, RefNo: 'TXN-001', Active: true },
    updateData:  { RefNo: 'TXN-002' },
    existingRow: { PaymentModeId: UUID, RefNo: 'TXN-001', Comment: null },
  },
  {
    name: 'paymentdetail',
    servicePath: '../../modules/paymentdetail/paymentdetail.service',
    httpPath: '/api/paymentdetails',
    exports: STD,
    createData:  { AccountTypeBaseId: UUID, TransactionDetailLogId: UUID, TotalAmount: '1000', GrossAmount: '1000', Active: true },
    updateData:  { TotalAmount: '2000' },
    existingRow: { AccountTypeBaseId: UUID, TransactionDetailLogId: UUID, TotalAmount: '1000', GrossAmount: '1000', UserId: null },
  },
  {
    name: 'paymentbreakup',
    servicePath: '../../modules/paymentbreakup/paymentbreakup.service',
    httpPath: '/api/paymentbreakups',
    exports: STD,
    createData:  { AccountTypeBaseId: UUID, PaymentDetailId: UUID, PaymentModeTransactionDetailId: UUID, PaymentReceivedTypeId: UUID, Timestamp: '2026-05-31T10:00:00.000Z', Active: true },
    updateData:  { Active: false },
    existingRow: { AccountTypeBaseId: UUID, PaymentDetailId: UUID, PaymentModeTransactionDetailId: UUID, PaymentReceivedTypeId: UUID, Timestamp: '2026-05-31 10:00:00', UserId: null },
  },

  // ─── POS (Front Desk) modules ─────────────────────────────────────────────
  {
    name: 'posfloor',
    servicePath: '../../modules/posfloor/posfloor.service',
    httpPath: '/api/pos/floors',
    exports: POS,
    createData:  { Name: 'Main Dining', Active: true },
    updateData:  { Name: 'Rooftop' },
    existingRow: { Name: 'Main Dining', BranchDetailId: null },
  },
  {
    name: 'postable',
    servicePath: '../../modules/postable/postable.service',
    httpPath: '/api/pos/tables',
    exports: POS,
    createData:  { Name: 'Table 1', Active: true },
    // Status is a fixed enum (POS_TABLE_STATUSES) — capitalised, matching what
    // the frontend writes in Billing.js / Tables.js.
    updateData:  { Status: 'Occupied' },
    existingRow: { Name: 'Table 1', FloorId: null, Capacity: 4, Status: 'free', CurrentOrderId: null, BranchDetailId: null },
  },
  {
    name: 'poschannel',
    servicePath: '../../modules/poschannel/poschannel.service',
    httpPath: '/api/pos/channels',
    exports: POS,
    createData:  { Name: 'Dine In', Code: 'dinein', SortOrder: 1, Active: true },
    updateData:  { Name: 'Takeaway' },
    existingRow: { Name: 'Dine In', Code: 'dinein', Description: null, SortOrder: 1 },
  },
  {
    name: 'posvariant',
    servicePath: '../../modules/posvariant/posvariant.service',
    httpPath: '/api/pos/variants',
    exports: POS,
    createData:  { Name: 'Half', Code: 'half', SortOrder: 1, Active: true },
    updateData:  { Name: 'Full' },
    existingRow: { Name: 'Half', Code: 'half', Description: null, SortOrder: 1, Price: null },
  },
  {
    name: 'posfoodtype',
    servicePath: '../../modules/posfoodtype/posfoodtype.service',
    httpPath: '/api/pos/food-types',
    exports: POS,
    createData:  { Name: 'Veg', Code: 'veg', SortOrder: 1, IsVeg: true, Active: true },
    updateData:  { Name: 'Non-Veg', IsVeg: false },
    existingRow: { Name: 'Veg', Code: 'veg', Description: null, SortOrder: 1, IsVeg: true },
  },
  {
    name: 'positemmeta',
    servicePath: '../../modules/positemmeta/positemmeta.service',
    httpPath: '/api/pos/item-meta',
    exports: POS,
    createData:  { ItemDetailId: UUID, FoodTypeId: UUID, CostInfoId: UUID, ChannelIds: [UUID], VariantIds: [UUID], BranchDetailId: UUID, Active: true },
    updateData:  { FoodTypeId: UUID },
    existingRow: { ItemDetailId: UUID, FoodTypeId: UUID, CostInfoId: UUID, Channels: { dinein: true }, Prices: { dinein: 100 }, Variants: [], BranchDetailId: UUID },
  },
  {
    name: 'poscustomer',
    servicePath: '../../modules/poscustomer/poscustomer.service',
    httpPath: '/api/pos/customers',
    exports: POS,
    createData:  { Name: 'Rahul Verma', Phone: '9876543210', Active: true },
    updateData:  { LoyaltyPoints: 100 },
    existingRow: { Name: 'Rahul Verma', Phone: '9876543210', Email: null, Visits: 0, TotalSpent: 0, LoyaltyPoints: 0, BranchDetailId: null },
  },
  {
    name: 'posorder',
    servicePath: '../../modules/posorder/posorder.service',
    httpPath: '/api/pos/orders',
    exports: POS,
    createData:  { OrderNo: 'ORD-1', Active: true },
    updateData:  { Status: 'closed' },
    existingRow: { OrderNo: 'ORD-1', TableId: null, CustomerId: null, OrderType: 'dinein', Status: 'open', Items: null, SubTotal: 0, TaxAmount: 0, Total: 0, BranchDetailId: null },
  },
  {
    name: 'poskot',
    servicePath: '../../modules/poskot/poskot.service',
    httpPath: '/api/pos/kots',
    exports: POS,
    createData:  { KotNo: 'KOT-1', Active: true },
    updateData:  { Status: 'ready' },
    existingRow: { KotNo: 'KOT-1', OrderId: null, TableId: null, Items: null, Status: 'pending', FiredAt: null, BranchDetailId: null },
  },
  {
    name: 'posbill',
    servicePath: '../../modules/posbill/posbill.service',
    httpPath: '/api/pos/bills',
    exports: POS,
    createData:  { BillNo: 'BILL-1', Active: true },
    updateData:  { Status: 'paid' },
    existingRow: { BillNo: 'BILL-1', OrderId: null, SubTotal: 0, TaxAmount: 0, Discount: 0, Total: 0, Payments: null, Status: 'unpaid', SettledAt: null, BranchDetailId: null },
  },
  {
    name: 'posonlineorder',
    servicePath: '../../modules/posonlineorder/posonlineorder.service',
    httpPath: '/api/pos/online-orders',
    exports: POS,
    createData:  { Platform: 'Swiggy', Active: true },
    updateData:  { Status: 'accepted' },
    existingRow: { Platform: 'Swiggy', ExternalRef: null, Status: 'new', Payload: null, BranchDetailId: null },
  },
  {
    name: 'posfeedback',
    servicePath: '../../modules/posfeedback/posfeedback.service',
    httpPath: '/api/pos/feedback',
    exports: POS,
    createData:  { CustomerName: 'Rahul Verma', Rating: 5, Active: true },
    updateData:  { Rating: 4 },
    existingRow: { CustomerId: null, CustomerName: 'Rahul Verma', Rating: 5, Comments: null, BranchDetailId: null },
  },
  {
    name: 'postoken',
    servicePath: '../../modules/postoken/postoken.service',
    httpPath: '/api/pos/tokens',
    exports: POS,
    createData:  { TokenNumber: 1, Active: true },
    updateData:  { Status: 'called' },
    existingRow: { TokenNumber: 1, OrderId: null, Status: 'waiting', BranchDetailId: null },
  },
  {
    name: 'posexpense',
    servicePath: '../../modules/posexpense/posexpense.service',
    httpPath: '/api/pos/expenses',
    exports: POS,
    createData:  { Category: 'Groceries', Amount: 500, Active: true },
    updateData:  { Amount: 600 },
    existingRow: { Category: 'Groceries', Description: null, Amount: 500, ExpenseDate: null, BranchDetailId: null },
  },
  {
    name: 'posstaff',
    servicePath: '../../modules/posstaff/posstaff.service',
    httpPath: '/api/pos/staff',
    exports: POS,
    createData:  { Name: 'Head Chef', Role: 'Kitchen', Active: true },
    updateData:  { Role: 'Manager' },
    existingRow: { Name: 'Head Chef', Role: 'Kitchen', Phone: null, Email: null, BranchDetailId: null },
  },
];

module.exports = registry;
